services:
  postgres-dev:
    image: postgres:15
    ports:
      - '5837:5432' # expose pg on port 5832 to not collide with pg from elswhere
    restart: always
    volumes:
      - ./volumes/dev/db:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
  postgres-test:
    image: postgres:15
    ports:
      - '5838:5432' # expose pg on port 5832 to not collide with pg from elswhere
    restart: always
    volumes:
      - ./volumes/test/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  db_data:
